package setup

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/drolosoft/cmux-resurrect/internal/client"
)

// DescribeBackend returns a human-readable name for the detected backend.
func DescribeBackend(b client.DetectedBackend) string {
	switch b {
	case client.BackendCmux:
		return "cmux"
	case client.BackendGhostty:
		return "Ghostty"
	default:
		return "unknown"
	}
}

// GenerateDefaultConfig returns TOML config content with the given defaults.
func GenerateDefaultConfig(watchInterval string, maxAutosaves int) string {
	return fmt.Sprintf(`# crex configuration
# Generated by crex setup wizard.

# How often to auto-save sessions (e.g. "5m", "30s").
watch_interval = %q

# Maximum number of auto-saves to keep per session.
max_autosaves = %d
`, watchInterval, maxAutosaves)
}

// WriteConfigIfNotExists writes a default config file at path if it does not
// already exist. Returns (true, nil) if the file was created, (false, nil) if
// it already existed, or (false, error) on any write failure.
func WriteConfigIfNotExists(path, watchInterval string, maxAutosaves int) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		// File already exists — skip.
		return false, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("create config dir: %w", err)
	}

	content := GenerateDefaultConfig(watchInterval, maxAutosaves)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write config: %w", err)
	}
	return true, nil
}
